export const STUDENTS = [
  "Abdul Khadar M S",
  "Abhinand Pk",
  "Abhirami Menoth",
  "Abin Mathew",
  "Ajaykrishnan S",
  "Akhosh Sajeev",
  "Aleesha A",
  "Alex Antony",
  "Amal M",
  "Amrutha Suresh",
  "Amruth Krishnan M",
  "Anand Sanker K G",
  "Anju V S",
  "Anseef",
  "Ansha Uthaman",
  "Anuradha K P",
  "Arathi Krishnan P U",
  "Archana P",
  "Arundhathy Mohan",
  "Arya A S",
  "Aswathy T S",
  "Athira Muralidharan",
  "Binil Babu",
  "Dhiya Fathima",
  "Dildiya Ss",
  "Fathima R",
  "Gopika Vinu",
  "Jisin Joseph Chacko",
  "Jobin Mathew",
  "Kailas Nadh R",
  "Kevin Monachan",
  "Kiran Ps",
  "Krishna Prasad S",
  "Meenu M",
  "Megha M S",
  "Midhun Madhu",
  "Muhammed Afthab S",
  "Murali Krishna",
  "Nandana S",
  "Nitheesh B",
  "Nithya Hari",
  "Prasheeja Pt",
  "Rahul G",
  "Rahul M Nair",
  "Rohit S Cherian",
  "Sabin Sajeeve Sam",
  "Salmanul Fariz N K",
  "Sanika Thampi",
  "Sanjana",
  "Shahanas M A",
  "Sradha S Vijay",
  "Sreedev S Kurup",
  "Thahina N",
  "Tony K Mathew",
  "Vishnu Tr"
]
